language: rust
os:
  - linux
  - osx
sudo: required
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - RUSTC=$HOME/rust/bin/rustc RUSTDOC=$HOME/rust/bin/rustdoc RUST_BACKTRACE=1
script:
  - cargo build --verbose
  - sudo -E /home/travis/rust/bin/cargo test --verbose