language: rust
os:
  - linux
  - osx
sudo: required
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
env:
  - CARGO=$HOME/rust/bin/cargo RUSTC=$HOME/rust/bin/rustc RUSTDOC=$HOME/rust/bin/rustdoc RUST_BACKTRACE=1
script:
  - echo $TRAVIS_RUST_VERSION
  - ([ $TRAVIS_RUST_VERSION == nightly ] || $CARGO build --verbose)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || $CARGO build --verbose --features clippy)
  - ([ $TRAVIS_RUST_VERSION == nightly ] || sudo $CARGO test --verbose)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || sudo $CARGO test --verbose --features clippy)
