language: rust
os:
  - linux
  - osx
sudo: required
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
env:
  - RUST_BACKTRACE=1 CARGO_PATH=`whereis -b cargo | cut -d ' ' -f 2`
script:
  - ([ $TRAVIS_RUST_VERSION == nightly ] || cargo build --verbose)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo build --verbose --features clippy)
  - ([ $TRAVIS_RUST_VERSION == nightly ] || sudo $CARGO_PATH test --verbose)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || sudo $CARGO_PATH test --verbose --features clippy)
