language: rust
os:
  - linux
  - osx
sudo: required
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
env:
  - RUST_BACKTRACE=1
script:
  - ([ $TRAVIS_RUST_VERSION == nightly ] || cargo build --verbose)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo build --verbose --features clippy)
  - ([ $TRAVIS_RUST_VERSION == nightly ] || sudo cargo test --verbose)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || sudo cargo test --verbose --features clippy)
